#! /usr/bin/env python
# -*- encoding:utf-8 -*-

"""
Usage:
   lys deploy-listener <event> <function> (<regexp> | (<field> <condition> \
<value>)...) [-w <webhook>]
   lys destroy-listener
   lys start-listening [-p <port>]
   lys restart-listeners
   lys stop-listening
   lys grant <public-key>...
   lys show-log
   lys public-ip

Options:
-w --webhook=<webhook> : the peer registering the webhook
-p --port=<port>       : the port used for listening srv [default: 5001]

Subcommands:
   deploy-listener   : link a webhook <event> with a python <function>
   destroy-listener  : unlink webhook <event> from python <function>
   start-listening   : start/restart listener server
   restart-listeners : restart listener server
   stop-listening    : stop listener server
   grant             : allow remote controle to public key owner
   show-log          : show server log
   public-ip         : get public ip
"""

import os
import sys
import docopt
import binascii
import traceback

# add git installation
sys.path.append(os.path.abspath(os.path.expanduser("~/ark-listener")))
# add parent path if executed from git structure
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

import lystener
import cSecp256k1 as secp256k1
from lystener import server, rest, checkPluginDependencies
from lystener.client import deploy_listener


def public_ip(args={}, **options):
    public_ip = rest.GET.plain(peer="https://www.ipecho.net").get(
        "raw", lystener.getPublicIp()
    )
    sys.stdout.write("%s\n" % public_ip)
    sys.stdout.flush()


def start_listening(args={}, **options):
    checkPluginDependencies()
    # remove salt file
    salt = os.path.join(lystener.JSON, "salt")
    if os.path.exists(salt):
        os.remove(salt)
    server.deploy(port=options["port"])


def stop_listening(args={}, **options):
    os.system("sudo systemctl stop lys")


def restart_listeners(args={}, **options):
    checkPluginDependencies()
    # remove salt file
    salt = os.path.join(lystener.JSON, "salt")
    if os.path.exists(salt):
        os.remove(salt)
    os.system("sudo systemctl restart lys")


def show_log(args={}, **options):
    os.system("sudo journalctl -u lys -ef")


def grant(args={}, **options):
    auth = lystener.loadJson("auth")
    if not len(auth):
        auth = []
    for elem in args.get("<public-key>", []):
        try:
            secp256k1.point_from_encoded(binascii.unhexlify(elem))
        except Exception:
            wallet = rest.GET.api.wallets(
                elem, peer="https://explorer.ark.io:8443"
            ).get("data", {})
            puk = wallet.get("publicKey", None)
            if puk is not None:
                auth.append(wallet["publicKey"])
                lystener.logMsg(
                    "%s granted as %s" % (elem, wallet["publicKey"])
                )
            else:
                lystener.logMsg("%s can't be granted" % elem)
        else:
            lystener.logMsg("%s granted" % elem)
            auth.append(elem)
    lystener.dumpJson(list(set(auth)), "auth")


def destroy_listener(args={}, **options):
    """
    unlink blockchain event from a id list.
    """
    pairs = {}
    for name in [n for n in os.listdir(lystener.JSON) if n.endswith(".json")]:
        data = lystener.loadJson(name)
        if "id" in data:
            pairs[data["id"]] = name.replace(".json", "")

    id_ = lystener.chooseItem(
        "Select listener to destroy:",
        *[v for v in pairs.keys() if v]
    )
    if not id_:
        return
    json_name = "%s.json" % pairs[id_]

    # load webhook configuration
    webhook = lystener.loadJson(json_name)
    # condition bellow checks if webhook configurations is found
    try:
        if webhook.get("peer", False):
            # delete webhook using its id and parent peer
            rest.DELETE.api.webhooks(
                "%s" % webhook["id"], peer=webhook["peer"]
            )
            # delete the webhook configuration
            os.remove(os.path.join(lystener.JSON, json_name))
            lystener.logMsg("%s webhook destroyed" % id_)
        else:
            lystener.logMsg("%s webhook not found" % id_)
    except Exception as error:
        lystener.logMsg("%s" % webhook)
        lystener.logMsg("%r\n%s" % (error, traceback.format_exc()))


# command line execution
########################
if __name__ == "__main__":

    FILTER = {
        "--multiple": lambda value: value,
        "--condition": lambda value: value,
        "--field": lambda value: value,
        "--value": lambda value: value,
        "--webhook": lambda value: value,
        "--port": lambda value: value,
        "<regexp>": lambda value: getattr(value, "pattern", value)
    }

    # will get the first argument which is neither a value neither an option
    def getAction(args):
        for action in [k for k in args if k[0] not in ["-", "<"]]:
            if args[action] is True:
                return action
        return False

    # will rename --multi-word-option to multi_word_option
    def getOptions(args):
        options = {}
        for option, value in [
            (k, v) for k, v in args.items() if k.startswith("--")
            and v is not None
        ]:
            options[option[2:].replace("-", "_")] = value
        return dict((k, v) for k, v in options.items() if v is not None)

    # see http://docopt.org
    args = docopt.docopt(__doc__, argv=sys.argv[1:])
    for key, cast in [(k, c) for k, c in FILTER.items() if k in args]:
        args[key] = cast(args[key])

    action = getAction(args)
    options = getOptions(args)

    if action:
        # rename multi-word-action to multi_word_action
        func = getattr(sys.modules[__name__], action.replace("-", "_"))
        if callable(func):
            func(args, **options)
